- name: Deploy all analytics services to a single node
  hosts: all
  sudo: True
  gather_facts: True
  roles:
    - hadoop_master
    - hive
    - sqoop
  post_tasks:
    - name: install mysql locally
      apt: pkg=mysql-server-5.5 state=present
